# Generated by Django 5.2.1 on 2025-10-02 08:13

from django.db import migrations
from django.utils.text import slugify


def populate_tag_slugs(apps, schema_editor):
    """
    Populate the slug field for existing tags with a unique slug based on name
    """
    Tag = apps.get_model('posts', 'Tag')
    for tag in Tag.objects.all():
        base_slug = slugify(tag.name)
        slug = base_slug
        counter = 1
        
        # Keep checking until we find a unique slug
        while Tag.objects.filter(slug=slug).exclude(id=tag.id).exists():
            # Create a new slug with a counter appended
            slug = f"{base_slug}-{counter}"
            counter += 1
            
        tag.slug = slug
        tag.save()


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_bookmark_category_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_tag_slugs, migrations.RunPython.noop),
    ]
